CREATE TABLE ANNOTATION (ID  BIGSERIAL NOT NULL, CREATEDAT TIMESTAMP WITHOUT TIME ZONE, UPDATEDAT TIMESTAMP WITHOUT TIME ZONE, USERCREATED VARCHAR, USERUPDATED VARCHAR, TAGS VARCHAR, TEXT VARCHAR NOT NULL, TITLE VARCHAR, PRIMARY KEY (ID));
CREATE TABLE CHARACTERS_ANNOTATION (ANNOTATION_ID INT8 NOT NULL, CHARACTER_ID INT8);
CREATE TABLE COMMENT (ID  BIGSERIAL NOT NULL, INDEXREFERENCE INT8, LENGTHREFERENCE INT8, TEXT VARCHAR NOT NULL, TEXTREFERENCE VARCHAR NOT NULL, ANNOTATION_ID INT8 NOT NULL, PRIMARY KEY (ID));
CREATE TABLE EVENTS_ANNOTATION (ANNOTATION_ID INT8 NOT NULL, LOCALE_ID INT8);
CREATE TABLE LOCALES_ANNOTATION (ANNOTATION_ID INT8 NOT NULL, LOCALE_ID INT8);
ALTER TABLE IF EXISTS CHARACTERS_ANNOTATION ADD CONSTRAINT FK1_CHARACTERS_ANNOTATION FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION;
ALTER TABLE IF EXISTS COMMENT ADD CONSTRAINT FK1_COMMENT FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION;
ALTER TABLE IF EXISTS EVENTS_ANNOTATION ADD CONSTRAINT FK1_EVENTS_ANNOTATION FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION;
ALTER TABLE IF EXISTS LOCALES_ANNOTATION ADD CONSTRAINT FK1_LOCALES_ANNOTATION FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION;
